### PR TITLE
OnePlus 3/3t

### PR DESCRIPTION
**Pull request by xlxfoxxlx**
still need to add repos to jdc org so device tree isnt ready but this part is. also simplify call for makefile.

### CODE REVIEW

**Comment by smeroni68** [comment]
You can merge directly when changes are fine.

**Comment by xlxfoxxlx** [comment]
its all ready just want to confirm the lunch call with @B--B

**Comment by smeroni68** [comment]
OK.

**Comment by MRTHAKER** [comment]
someone merge my Pull request

**Comment by smeroni68** [comment]
You are under evaluation... and pushing for an action is not a good point. Oneplus devices has been integrated in JDC... as the respective devs. 
You are just a builder of the rom, so for now stay as unofficial as I already asked you. Thanks.

**Comment by B--B** [comment]
Hi there! sorry guys but i'm so busy in these days, will be back in a few days, hopefully before google release the new tag :)
These changes sounds good to me, even if user builds now compiles fine logcat is still broken so can't be shipped or used for debugging, better not show user builds for now!
I will merge this now, just 3 things/questions:
1 - https://github.com/AOSP-JF-MM/platform_device_oneplus_oneplus3/blob/aosp-7.1.2/jdc.dependencies#L3 we have our fork of this: https://github.com/AOSP-JF-MM/platform_device_oppo_common can we use this instead of an external repo? :)
2 - https://github.com/AOSP-JF-MM/platform_device_oneplus_oneplus3/blob/aosp-7.1.2/jdc.dependencies#L8 Not sure if this must be forked, probably defconfig should be regenerated with aosp as localversion?
3 - https://github.com/AOSP-JF-MM/platform_device_oneplus_oneplus3/blob/aosp-7.1.2/jdc.dependencies#L8 Now that we compile configpanel for multiple devices i'm considering to fork this and use it for all our devices, but i must update gemini configpanel first :)

**Comment by xlxfoxxlx** [comment]
sounds good just wanted to get it setup ill redo depends and can add the repos to jdc

**Comment by MRTHAKER** [comment]
someone on google plus asked me to make pull request so i did.
ANd what else i need to do for making rom official?

**Comment by smeroni68** [comment]
@MRTHAKER: Seems you asked and @dkati posted... but finally... why do you want to have Official "tag"? Sorry, but official means becoming an active JDCTeam member... Why Unofficial isn't good for you?
You builded the rom, it works... why official will make a difference? We, anyway, "hired" OnePlus X and 3/3T experienced developers to power the team, to help main dev @B--B on development (lack of free time is the real problem).
From your xda profile, seems you aren't a developer, but a user with a pc able to build all the roms around,
No offence, but, our source code is free published on github also for users (like you) that want to play and build... but this do not means that everyone that is able to build the rom will get official status.

Official = JDCTeam developer member
Unofficial = everyone else

That's the real answer.

**Pull request merged**
