### PR TITLE
Copyrights and README

### PR DESCRIPTION
**Pull request by MZO9400**
We're JDCTeam AOSP, 2017

### CODE REVIEW

**Comment by smeroni68** [comment]
You already merged!!

**Comment by MZO9400** [comment]
No, not into the aosp-7.1.2 branch. This is a test branch (readme)

Was waiting for your approval/merge

**Comment by smeroni68** [comment]
Oops... I see!!

**Comment by B--B** [comment]
For me it's ok :) ,only thing we should keep CM copyright and our initial copyright year, something like
Copyright (c) 2015-2017, The Jflte DevConnection Team
Copyright (c) 2015, The CyanogenMod project

**Comment by MZO9400** [comment]
Ah yes! It should've been like that

**Comment by B--B** [comment]
Once you made the change feel free to push it directly in main branch, for me is good! :+1:

**Pull request merged**
